apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.controlPlane.serviceTokenSecretName }}
  namespace: {{ .Release.Namespace }}
stringData:
  .env: |
    {{- range $key, $value := .Values.dotenv }}
    {{ $key }}="{{ $value }}"
    {{- end }}
